### ISSUE TITLE
Organization of Content on Home Page

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-chibitronics#144]
Need to move things around:
- Tutorials - should only be stuff that runs in our step-by-step tutorial engine
- Examples - block or JS code samples (load in editor)
- Instructions - make instructions (load in new tab)
- Guides - this should be the Book or other Courses/Lessons

I don't get where there's a the "Love to Code" section?
And I would rather use the skill level labels/ribbons we talked about (beginner, intermediate, advanced) on the cards, rather than have a separate Advanced section.

**Comment by ganicke** [comment]
RE: https://github.com/Microsoft/pxt-adafruit/issues/630

**Comment by ganicke** [comment]
Close this?

The card properties requested were added past this core version and this editor is not actively maintained now.

**Comment by Jaqster** [comment]
Yes, close.
