### ISSUE TITLE
Color dropdown for dim?

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-chibitronics#182]
We have a dropdown for the rbg color block
![image](https://user-images.githubusercontent.com/4175913/36043474-4c05d436-0d84-11e8-9efe-83c6a1486d2b.png)
![image](https://user-images.githubusercontent.com/4175913/36045689-673d5196-0d8b-11e8-9b17-fae2530a03a1.png)

**Comment by abchatra** [comment]
fixed
