### ISSUE TITLE
analog read mapping is not 0-100?

### ISSUE THREAD

**Issue by nataliefreed** [Microsoft/pxt-chibitronics#191]
Analog readings on voltages from 0 to 3V appear to be mapped to 0-400(ish) rather than 0-100. For example, if I run the code below to print analog read values to the Scope, a 3 volt reading (+3V pin connected to pin 0) shows up as 401, rather than 100 as I would have expected. I've tried this with both release and beta versions. Am I missing something or could this be a bug? Thanks!

<img width="300" alt="screen shot 2018-02-20 at 3 31 47 pm" src="https://user-images.githubusercontent.com/3833816/36450752-89ddf5c6-1654-11e8-92b1-7b709e606ad1.png">

<img width="416" alt="screen shot 2018-02-20 at 3 32 07 pm" src="https://user-images.githubusercontent.com/3833816/36450750-89bc89fe-1654-11e8-8324-8cf756843c61.png">

<img width="400" alt="chibi scope" src="https://user-images.githubusercontent.com/3833816/36450812-c4c99ac8-1654-11e8-986a-95e4a9c9a3bc.jpg">

**Comment by pelikhan** [comment]
@bunnie  When is the range of data returned by ``::analogRead``?

**Comment by xobs** [comment]
We follow the Arduino convention and default to 10 bits (0..1024), but support 12 bit resolution (0..4096).  A function exists ::analogReadResolution(int bits) to change the resolution, which could be called at the start of the program, or you could divide everything by four in ts.

**Comment by pelikhan** [comment]
Same convention here so we’re missing / 4.

**Comment by samelhusseini** [comment]
@xobs I've followed this through and it looks like our assumption that the OS ::analogRead function is returning a value between 0 and 255. 
I want to double check on a couple of assumptions to make sure we're consistent. 
it sounds like from your previous comment that the value returned by the OS analogRead is between 0 and 1024. That's okay I can update that assumption from our end, but what about analogWrite. Does it expect a value between 0 and 1024 or does is it inconsistent and expects a value between 0 an 255. 
Please clarify.

**Comment by xobs** [comment]
`::analogRead()` returns a value between 0 and 1023 inclusive.  The OS-level implementation is at https://github.com/chibitronics/ltc-os/blob/master/orchard/arduino-io.c#L412, and you can see `::analogReadResolution()` can be used to increase the resolution to up to 12 bits (0..4095).

`::analogWrite()` also mimics Arduino's implementation, and you're right the range is different.  The `::analogWrite()` function expects a value between (0..255).

**Comment by samelhusseini** [comment]
Makes perfect sense. I think were we went wrong was in assuming the underlying read and write had the same ranges. 
Now that we know the ranges of the underlying APIs. What should we expose to users. 
We've already agreed that the high level 'read level' and 'set level' APIs should have a range of 0-100 as per Natalie's request, but what should the ranges of the lower level APIs be.
I see two options here, we stay consistent with the OS and give the user the same granularity, (0..1023) for read (0.255) for write. or we try and make the two APIs consistent, mapping levels to one of the two ranges.
Thoughts? @xobs @nataliefreed @pelikhan

**Comment by nataliefreed** [comment]
My two cents:
read level and set level 0-100 for beginner-level simplicity.
analogRead and analogWrite 0-1023 and 0-255 to match Arduino conventions, since those functions match Arduino syntax, and also to have access to higher resolution reads/writes.
Checking in with @jieq as well.

**Comment by pelikhan** [comment]
We should align with MakeCode which is 0..1023 both on read/write.

________________________________

**Comment by samelhusseini** [comment]
@nataliefreed are you also okay if I change the top level read block to say "read level" instead of "read analog", in order to make it consistent with "set level" (for analog).
