### ISSUE TITLE
The text of item "Buy" is "Help"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-chibitronics#206]
**Repro steps:**
• Navigate to https://makecode.chibitronics.com/#editor
• Click "Help" and then focus on each items one by one

**Expected result:**
The text of each item should be same as each item
**Actual result:**
The text of item "Buy" is "Help"
![1](https://user-images.githubusercontent.com/23466737/39856972-55bb4004-5421-11e8-8a61-4fd6ed53511a.gif)

**Comment by samelhusseini** [comment]
Fixed in latest.
