### ISSUE TITLE
Opened getting started tutorial and had no blocks in toolbox

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt-chibitronics#208]
Only available block was "on start". Tested with beta on Chromebook

**Comment by samelhusseini** [comment]
Repros everywhere.

**Comment by samelhusseini** [comment]
I wonder if this has something to do with the extended toolbox.

**Comment by samelhusseini** [comment]
The two used blocks that it's returning are typescript_statement and on_start
Maybe a decompilation problem with the tutorial?

**Comment by riknoll** [comment]
It decompiles correctly in the hint
