### ISSUE TITLE
There is no closing button when opening examples under "Tutorials", "Guides" and "Advanced"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-chibitronics#210]
**Repro steps:**
• Open https://makecode.chibitronics.com/beta
• Navigate to "Tutorials", "Examples", "Love to Code", "Guides", "Advanced" and open examples under them

**Expected result:**
Every opened example should have a closing button on the opened window
![compare5](https://user-images.githubusercontent.com/23466737/40170364-bbb828e0-59b7-11e8-950a-1de62dbf1418.PNG)

**Actual result:**
 There is no closing button when opening examples under "Tutorials", "Guides" and "Advanced"
![issue5](https://user-images.githubusercontent.com/23466737/40170376-c776d3de-59b7-11e8-81c4-d405f089ae1d.PNG)

**Comment by samelhusseini** [comment]
It's there, but it's white. We need to think through a fix for this.

**Comment by Helen09** [comment]
Closed as fixed
