### ISSUE TITLE
weird error message in console

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-chibitronics#218]
![image](https://user-images.githubusercontent.com/4175913/40256305-e14fda52-5a9e-11e8-9cde-e8d82e131961.png)

![image](https://user-images.githubusercontent.com/4175913/40256334-f18c7c54-5a9e-11e8-91ea-1ee50c35b4f9.png)

**Comment by samelhusseini** [comment]
Removed console log.
